"""Chronic-cohort code catalog — authoring source of truth.

Each entry declares a clinical concept and a medterm4ds search used to resolve
the concept to an active code in UMLS 2026AA. The resolver
(resolve-catalog.py) picks the best search hit, records official display
names, and flags anything ambiguous for manual review. No code enters a
fixture without passing through this catalog.

Entry: (id, kind, system, search, expect)
  expect = code I believe is correct; if search disagrees the row is flagged
  for review. Final pick is always an active UMLS concept.
"""

CATALOG = [
    # ---------------- Conditions: respiratory ----------------
    ("cond.gout", "condition", "SNOMEDCT_US", "Gout", None, "90560007"),
    ("cond.schizophrenia", "condition", "SNOMEDCT_US", "Schizophrenia", None, "58214004"),
    ("icd.gout", "condition_icd10", "ICD10CM", "M10.9"),
    ("icd.schizophrenia", "condition_icd10", "ICD10CM", "F20.9"),
    ("med.allopurinol_300", "medication", "RXNORM", "allopurinol 300 MG Oral Tablet", None, "197320"),
    ("med.allopurinol_100", "medication", "RXNORM", "allopurinol 100 MG Oral Tablet", None, "197319"),
    ("med.colchicine_06", "medication", "RXNORM", "colchicine 0.6 MG Oral Tablet", None, "197541"),
    ("med.clozapine_100", "medication", "RXNORM", "clozapine 100 MG Disintegrating Oral Tablet", None, "476177"),
    ("lab.urate", "lab", "LNC", "Urate [Mass/volume] in Serum or Plasma", None, "3084-1"),
    ("lab.anc", "lab", "LNC", "Neutrophils [#/volume] in Blood", None, "26499-4"),
    ("lab.clozapine_level", "lab", "LNC", "Clozapine [Mass/volume] in Serum", None, "29370-4"),
    ("cond.asthma", "condition", "SNOMEDCT_US", "Asthma", "195967001"),
    ("cond.severe_persistent_asthma", "condition", "SNOMEDCT_US", "Severe persistent asthma", "426656000"),
    ("cond.moderate_persistent_asthma", "condition", "SNOMEDCT_US", "Moderate persistent asthma", None),
    ("cond.asthma_copd_overlap", "condition", "SNOMEDCT_US", "Asthma chronic obstructive pulmonary disease overlap syndrome", None),
    ("cond.allergic_rhinitis", "condition", "SNOMEDCT_US", "Allergic rhinitis", None),
    ("cond.atopic_dermatitis", "condition", "SNOMEDCT_US", "Atopic dermatitis", None, "24079001"),
    ("cond.chronic_sinusitis", "condition", "SNOMEDCT_US", "Chronic sinusitis", None, "40055000"),
    ("cond.copd", "condition", "SNOMEDCT_US", "Chronic obstructive lung disease", "13645005"),
    ("cond.copd_severe", "condition", "SNOMEDCT_US", "Very severe chronic obstructive pulmonary disease", None),
    ("cond.gerd", "condition", "SNOMEDCT_US", "Gastro-esophageal reflux disease", None),
    ("cond.osa", "condition", "SNOMEDCT_US", "Obstructive sleep apnea syndrome", "78275009"),
    ("cond.bronchiectasis", "condition", "SNOMEDCT_US", "Bronchiectasis", None),

    # ---------------- Conditions: cardiovascular ----------------
    ("cond.mi_history", "condition", "SNOMEDCT_US", "Myocardial infarction (disorder)", None),
    ("cond.STEMI", "condition", "SNOMEDCT_US", "Acute myocardial infarction", None, "57054005"),
    ("cond.hf", "condition", "SNOMEDCT_US", "Heart failure", "84114007"),
    ("cond.hfref_systolic", "condition", "SNOMEDCT_US", "Congestive heart failure, systolic", None),
    ("cond.afib", "condition", "SNOMEDCT_US", "Atrial fibrillation", "49436004"),
    ("cond.htn", "condition", "SNOMEDCT_US", "Essential hypertension", "59621000"),
    ("cond.hyperlipidemia", "condition", "SNOMEDCT_US", "Hyperlipidemia", "55822004"),
    ("cond.stroke_ischemic", "condition", "SNOMEDCT_US", "Cerebral infarction", None),
    ("cond.hemiparesis", "condition", "ICD10CM", "I69.359"),
    ("cond.carotid_stenosis", "condition", "SNOMEDCT_US", "Stenosis of carotid artery", None),
    ("cond.pad", "condition", "SNOMEDCT_US", "Peripheral vascular disease", None, "400047006"),
    ("cond.dvt_history", "condition", "SNOMEDCT_US", "Deep venous thrombosis", None, "128053003"),

    # ---------------- Conditions: endocrine/metabolic ----------------
    ("cond.t1dm", "condition", "SNOMEDCT_US", "Type 1 diabetes mellitus", None, "46635009"),
    ("cond.t2dm", "condition", "SNOMEDCT_US", "Type 2 diabetes mellitus", None, "44054006"),
    ("cond.diabetic_nephropathy", "condition", "SNOMEDCT_US", "Disorder of kidney due to diabetes mellitus", None, "127013003"),
    ("cond.diabetic_retinopathy", "condition", "SNOMEDCT_US", "Retinopathy due to diabetes mellitus", None, "4855003"),
    ("cond.obesity", "condition", "SNOMEDCT_US", "Obesity", "414915002"),
    ("cond.hypothyroidism", "condition", "SNOMEDCT_US", "Hypothyroidism", None, "40930008"),
    ("cond.hashimoto", "condition", "SNOMEDCT_US", "Hashimoto thyroiditis", None),
    ("cond.vitamin_d_deficiency", "condition", "SNOMEDCT_US", "Vitamin D deficiency", None),
    ("cond.b12_deficiency", "condition", "SNOMEDCT_US", "Vitamin B12 deficiency", None),
    ("cond.ckd", "condition", "SNOMEDCT_US", "Chronic kidney disease", None, "709044004"),
    ("cond.ckd3", "condition", "SNOMEDCT_US", "Chronic kidney disease stage 3", "433144002"),
    ("cond.ckd4", "condition", "SNOMEDCT_US", "Chronic kidney disease stage 4", None),
    ("cond.ckd5", "condition", "SNOMEDCT_US", "Chronic kidney disease stage 5", None),
    ("cond.esrd", "condition", "SNOMEDCT_US", "End stage renal disease", None),
    ("cond.pkd", "condition", "SNOMEDCT_US", "Autosomal dominant polycystic kidney disease", None, "765330003"),
    ("cond.anemia", "condition", "SNOMEDCT_US", "Anemia", "271737000"),
    ("cond.iron_def_anemia", "condition", "SNOMEDCT_US", "Iron deficiency anemia", "87522002"),
    ("cond.anemia_ckd", "condition", "SNOMEDCT_US", "Anemia of chronic kidney disease", None),
    ("cond.secondary_hyperparathyroidism", "condition", "SNOMEDCT_US", "Secondary hyperparathyroidism", None),

    # ---------------- Conditions: rheum/autoimmune ----------------
    ("cond.ra", "condition", "SNOMEDCT_US", "Rheumatoid arthritis", None, "69896004"),
    ("cond.sjogren", "condition", "SNOMEDCT_US", "Sjogren's syndrome", None),
    ("cond.sle", "condition", "SNOMEDCT_US", "Systemic lupus erythematosus", "55464009"),
    ("cond.lupus_nephritis", "condition", "SNOMEDCT_US", "SLE glomerulonephritis syndrome", None, "68815009"),
    ("cond.antiphospholipid_syndrome", "condition", "SNOMEDCT_US", "Antiphospholipid syndrome", None),
    ("cond.crohn", "condition", "SNOMEDCT_US", "Crohn's disease", "34000006"),
    ("cond.anal_fistula", "condition", "ICD10CM", "K60.3"),
    ("cond.celiac", "condition", "SNOMEDCT_US", "Celiac disease", None),
    ("cond.psoriasis", "condition", "SNOMEDCT_US", "Psoriasis", "9014002"),
    ("cond.psoriatic_arthritis", "condition", "SNOMEDCT_US", "Psoriatic arthritis", None),

    # ---------------- Conditions: psych/neuro ----------------
    ("cond.bipolar", "condition", "SNOMEDCT_US", "Bipolar disorder", "13746004"),
    ("cond.mdd", "condition", "SNOMEDCT_US", "Major depressive disorder", None),
    ("cond.gad", "condition", "SNOMEDCT_US", "Generalized anxiety disorder", None),
    ("cond.insomnia", "condition", "SNOMEDCT_US", "Insomnia", None, "193462001"),
    ("cond.epilepsy", "condition", "SNOMEDCT_US", "Epilepsy", None, "84757009"),
    ("cond.jme", "condition", "SNOMEDCT_US", "Juvenile myoclonic epilepsy", None),
    ("cond.adhd", "condition", "SNOMEDCT_US", "Attention deficit hyperactivity disorder", "406506008"),

    # ---------------- Conditions: other ----------------
    ("cond.osteoporosis", "condition", "SNOMEDCT_US", "Osteoporosis", "64859006"),
    ("cond.compression_fx", "condition", "SNOMEDCT_US", "Compression fracture of vertebra", None),
    ("cond.hcv", "condition", "SNOMEDCT_US", "Chronic hepatitis C", None),
    ("cond.cirrhosis", "condition", "SNOMEDCT_US", "Cirrhosis of liver", "19943007"),
    ("cond.thrombocytopenia", "condition", "ICD10CM", "D69.6"),
    ("cond.esophageal_varices", "condition", "SNOMEDCT_US", "Esophageal varices", None),
    ("cond.hiv", "condition", "SNOMEDCT_US", "Human immunodeficiency virus infection", None, "86406008"),
    ("cond.breast_cancer", "condition", "SNOMEDCT_US", "Malignant neoplasm of breast", None),
    ("cond.lymphedema", "condition", "ICD10CM", "I89.0"),
    ("cond.sickle_cell", "condition", "SNOMEDCT_US", "Sickle cell-hemoglobin SS disease", None, "127040003"),
    ("cond.sickle_crisis", "condition", "SNOMEDCT_US", "Hemoglobin SS disease with crisis", None, "417425009"),
    ("cond.bph", "condition", "SNOMEDCT_US", "Benign prostatic hyperplasia", None),
    ("cond.oa", "condition", "SNOMEDCT_US", "Osteoarthritis", None, "396275006"),
    ("cond.oa_knee", "condition", "SNOMEDCT_US", "Osteoarthritis of knee", None),
    ("cond.long_term_anticoag", "condition", "SNOMEDCT_US", "Long-term anticoagulant therapy", None),

    # ---------------- Conditions: ICD-10-CM coding (subset) ----------------
    ("icd.asthma", "condition_icd10", "ICD10CM", "J45.909", None),
    ("icd.asthma_severe", "condition_icd10", "ICD10CM", "J45.52", None),
    ("icd.copd", "condition_icd10", "ICD10CM", "J44.9", None),
    ("icd.copd_severe", "condition_icd10", "ICD10CM", "J44.1", None),
    ("icd.t2dm", "condition_icd10", "ICD10CM", "E11.9", None),
    ("icd.t2dm_ckd", "condition_icd10", "ICD10CM", "E11.22", None),
    ("icd.t1dm", "condition_icd10", "ICD10CM", "E10.9", None),
    ("icd.ckd4", "condition_icd10", "ICD10CM", "N18.4", None),
    ("icd.esrd", "condition_icd10", "ICD10CM", "N18.6", None),
    ("icd.mi_old", "condition_icd10", "ICD10CM", "I25.2", None),
    ("icd.STEMI", "condition_icd10", "ICD10CM", "I21.0", None),
    ("icd.afib", "condition_icd10", "ICD10CM", "I48.91", None),
    ("icd.hfref", "condition_icd10", "ICD10CM", "I50.21", None),
    ("icd.hfpef", "condition_icd10", "ICD10CM", "I50.33", None),
    ("icd.htn", "condition_icd10", "ICD10CM", "I10", None),
    ("icd.hyperlipidemia", "condition_icd10", "ICD10CM", "E78.5", None),
    ("icd.stroke", "condition_icd10", "ICD10CM", "I63.9", None),
    ("icd.hypothyroidism", "condition_icd10", "ICD10CM", "E03.9", None),
    ("icd.bipolar", "condition_icd10", "ICD10CM", "F31.9", None),
    ("icd.mdd", "condition_icd10", "ICD10CM", "F33.1", None),
    ("icd.gad", "condition_icd10", "ICD10CM", "F41.1", None),
    ("icd.epilepsy", "condition_icd10", "ICD10CM", "G40.909", None),
    ("icd.ra", "condition_icd10", "ICD10CM", "M06.9", None),
    ("icd.sle", "condition_icd10", "ICD10CM", "M32.9", None),
    ("icd.crohn", "condition_icd10", "ICD10CM", "K50.90", None),
    ("icd.cirrhosis", "condition_icd10", "ICD10CM", "K74.60", None),
    ("icd.hcv", "condition_icd10", "ICD10CM", "B18.2", None),
    ("icd.hiv", "condition_icd10", "ICD10CM", "B20", None),
    ("icd.sickle", "condition_icd10", "ICD10CM", "D57.00", None),
    ("icd.osteo", "condition_icd10", "ICD10CM", "M81.0", None),
    ("icd.breast_ca", "condition_icd10", "ICD10CM", "C50.911", None),
    ("icd.adhd", "condition_icd10", "ICD10CM", "F90.0", None),
    ("icd.obesity", "condition_icd10", "ICD10CM", "E66.9", None),
    ("icd.osa", "condition_icd10", "ICD10CM", "G47.33", None),
    ("icd.psoriasis", "condition_icd10", "ICD10CM", "L40.0", None),
    ("icd.tobacco", "condition_icd10", "ICD10CM", "F17.210", None),
    ("icd.ckd3", "condition_icd10", "ICD10CM", "N18.32", None),

    # ---------------- Medications: respiratory ----------------
    ("med.albuterol_hfa", "medication", "RXNORM", "albuterol 0.09 MG/ACTUAT Inhalation Aerosol", None, "801093"),
    ("med.fluticasone_110", "medication", "RXNORM", "fluticasone propionate 110 MCG/ACTUAT inhalation aerosol", None),
    ("med.fluticasone_salmeterol", "medication", "RXNORM", "fluticasone propionate 0.25 MG/ACTUAT / salmeterol 0.05 MG/ACTUAT Dry Powder Inhaler", None, "896188"),
    ("med.budesonide_formoterol", "medication", "RXNORM", "budesonide 160 MCG/ACTUAT / formoterol fumarate 4.5 MCG/ACTUAT inhalation aerosol", None),
    ("med.montelukast", "medication", "RXNORM", "montelukast 10 MG Oral Tablet", None),
    ("med.prednisone_10", "medication", "RXNORM", "prednisone 10 MG Oral Tablet", None),
    ("med.prednisone_20", "medication", "RXNORM", "prednisone 20 MG Oral Tablet", None),
    ("med.omalizumab", "medication", "RXNORM", "omalizumab 150 MG/1.2ML powder for solution", None),
    ("med.mepolizumab", "medication", "RXNORM", "mepolizumab 100 MG/ML powder for injection", None),
    ("med.fluticasone_nasal", "medication", "RXNORM", "fluticasone propionate 50 MCG/ACTUAT nasal spray", None),
    ("med.tiotropium", "medication", "RXNORM", "tiotropium 18 MCG inhalation powder", None),
    ("med.umeclidinium_vilanterol", "medication", "RXNORM", "umeclidinium 62.5 MCG / vilanterol 25 MCG inhalation powder", None),
    ("med.ipratropium_albuterol", "medication", "RXNORM", "ipratropium 0.5 MG/2.5ML / albuterol 2.5 MG/2.5ML inhalation solution", None),
    ("med.azithromycin_250", "medication", "RXNORM", "azithromycin 250 MG Oral Tablet", None),
    ("med.varenicline", "medication", "RXNORM", "varenicline 1 MG Oral Tablet", None),
    ("med.hydrocortisone_cream", "medication", "RXNORM", "hydrocortisone 2.5 % topical cream", None),
    ("med.cetirizine", "medication", "RXNORM", "cetirizine 10 MG Oral Tablet", None),

    # ---------------- Medications: cardiovascular ----------------
    ("med.aspirin_81", "medication", "RXNORM", "aspirin 81 MG Oral Tablet", None),
    ("med.ticagrelor_90", "medication", "RXNORM", "ticagrelor 90 MG Oral Tablet", None),
    ("med.atorvastatin_80", "medication", "RXNORM", "atorvastatin 80 MG Oral Tablet", None),
    ("med.atorvastatin_20", "medication", "RXNORM", "atorvastatin 20 MG Oral Tablet", None),
    ("med.metoprolol_succinate_25", "medication", "RXNORM", "metoprolol succinate 25 MG Extended Release Tablet", None),
    ("med.metoprolol_succinate_100", "medication", "RXNORM", "metoprolol succinate 100 MG Extended Release Tablet", None),
    ("med.lisinopril_10", "medication", "RXNORM", "lisinopril 10 MG Oral Tablet", "314076"),
    ("med.lisinopril_20", "medication", "RXNORM", "lisinopril 20 MG Oral Tablet", None),
    ("med.nitroglycerin_sl", "medication", "RXNORM", "nitroglycerin 0.4 MG/ACTUAT sublingual spray", None),
    ("med.amlodipine_5", "medication", "RXNORM", "amlodipine 5 MG Oral Tablet", None),
    ("med.metoprolol_tartrate_25", "medication", "RXNORM", "metoprolol tartrate 25 MG Oral Tablet", None),
    ("med.isosorbide_mono30", "medication", "RXNORM", "isosorbide mononitrate 30 MG Extended Release Tablet", None),
    ("med.sacubitril_valsartan_24_26", "medication", "RXNORM", "sacubitril 24 MG / valsartan 26 MG Oral Tablet", None),
    ("med.sacubitril_valsartan_49_51", "medication", "RXNORM", "sacubitril 49 MG / valsartan 51 MG Oral Tablet", None),
    ("med.sacubitril_valsartan_97_103", "medication", "RXNORM", "sacubitril 97 MG / valsartan 103 MG Oral Tablet", None),
    ("med.dapagliflozin_10", "medication", "RXNORM", "dapagliflozin 10 MG Oral Tablet", None),
    ("med.spironolactone_25", "medication", "RXNORM", "spironolactone 25 MG Oral Tablet", None),
    ("med.furosemide_40", "medication", "RXNORM", "furosemide 40 MG Oral Tablet", None, "313988"),
    ("med.furosemide_80", "medication", "RXNORM", "furosemide 80 MG Oral Tablet", None),
    ("med.apixaban_5", "medication", "RXNORM", "apixaban 5 MG Oral Tablet", None),
    ("med.warfarin_5", "medication", "RXNORM", "warfarin sodium 5 MG Oral Tablet", "855332"),
    ("med.carvedilol_125", "medication", "RXNORM", "carvedilol 12.5 MG Oral Tablet", None, "200032"),
    ("med.rosuvastatin_20", "medication", "RXNORM", "rosuvastatin 20 MG Oral Tablet", None),

    # ---------------- Medications: diabetes/metabolic ----------------
    ("med.metformin_500", "medication", "RXNORM", "metformin 500 MG Oral Tablet", None),
    ("med.metformin_er1000", "medication", "RXNORM", "metformin 1000 MG 24 Hour Extended Release Tablet", None),
    ("med.semaglutide_pen", "medication", "RXNORM", "1.5 ML semaglutide 1.34 MG/ML Pen Injector", None),
    ("med.insulin_lispro", "medication", "RXNORM", "insulin lispro 100 UNT/ML injection solution", None),
    ("med.insulin_glargine", "medication", "RXNORM", "insulin glargine 100 UNT/ML injection solution", None),
    ("med.levothyroxine_50", "medication", "RXNORM", "levothyroxine sodium 0.05 MG Oral Tablet", None, "966221"),
    ("med.levothyroxine_75", "medication", "RXNORM", "levothyroxine sodium 75 MCG Oral Tablet", None),
    ("med.levothyroxine_88", "medication", "RXNORM", "levothyroxine sodium 88 MCG Oral Tablet", None),
    ("med.epoetin_alfa", "medication", "RXNORM", "epoetin alfa 10000 UNT/ML injection solution", None),
    ("med.sevelamer_800", "medication", "RXNORM", "sevelamer carbonate 800 MG Oral Tablet", None),
    ("med.calcitriol_025", "medication", "RXNORM", "calcitriol 0.25 MCG Oral Capsule", None),
    ("med.cholecalciferol_2000", "medication", "RXNORM", "cholecalciferol 0.05 MG Oral Tablet", None, "801663"),

    # ---------------- Medications: transplant/CKD ----------------
    ("med.tacrolimus_1", "medication", "RXNORM", "tacrolimus 1 MG Oral Capsule", None),
    ("med.mycophenolate_500", "medication", "RXNORM", "mycophenolate mofetil 500 MG Oral Tablet", None),
    ("med.prednisone_5", "medication", "RXNORM", "prednisone 5 MG Oral Tablet", None),
    ("med.valganciclovir_450", "medication", "RXNORM", "valganciclovir 450 MG Oral Tablet", None),
    ("med.bactrim_ds", "medication", "RXNORM", "sulfamethoxazole 800 MG / trimethoprim 160 MG Oral Tablet", None),

    # ---------------- Medications: rheum/GI ----------------
    ("med.methotrexate_25", "medication", "RXNORM", "methotrexate 25 MG/ML injection solution", None),
    ("med.methotrexate_25mg", "medication", "RXNORM", "methotrexate sodium 2.5 MG Oral Tablet", None),
    ("med.folic_acid_1", "medication", "RXNORM", "folic acid 1 MG Oral Tablet", None),
    ("med.hydroxychloroquine_200", "medication", "RXNORM", "hydroxychloroquine 200 MG Oral Tablet", None),
    ("med.ibuprofen_600", "medication", "RXNORM", "ibuprofen 600 MG Oral Tablet", None),
    ("med.adalimumab_40", "medication", "RXNORM", "adalimumab 40 MG/0.4ML injection solution", None),
    ("med.infliximab_100", "medication", "RXNORM", "infliximab 10 MG/ML injection solution", None),
    ("med.azathioprine_50", "medication", "RXNORM", "azathioprine 50 MG Oral Tablet", None),
    ("med.ferrous_sulfate_325", "medication", "RXNORM", "ferrous sulfate 325 MG Oral Tablet", "310325"),
    ("med.lactulose", "medication", "RXNORM", "lactulose 667 MG/ML Oral Solution", None, "336731"),
    ("med.propranolol_20", "medication", "RXNORM", "propranolol 20 MG Oral Tablet", None),
    ("med.sofosbuvir_400", "medication", "RXNORM", "sofosbuvir 400 MG Oral Tablet", None),

    # ---------------- Medications: psych/neuro ----------------
    ("med.lithium_300", "medication", "RXNORM", "lithium carbonate 300 MG Oral Capsule", "197528"),
    ("med.lithium_er450", "medication", "RXNORM", "lithium carbonate 450 MG 24 Hour Extended Release Tablet", None),
    ("med.lamotrigine_100", "medication", "RXNORM", "lamotrigine 100 MG Oral Tablet", None),
    ("med.sertraline_50", "medication", "RXNORM", "sertraline 50 MG Oral Tablet", None),
    ("med.sertraline_100", "medication", "RXNORM", "sertraline 100 MG Oral Tablet", None),
    ("med.trazodone_50", "medication", "RXNORM", "trazodone 50 MG Oral Tablet", None),
    ("med.levetiracetam_500", "medication", "RXNORM", "levetiracetam 500 MG Oral Tablet", None),
    ("med.methylphenidate_er20", "medication", "RXNORM", "methylphenidate 20 MG 24 Hour Extended Release Tablet", None),

    # ---------------- Medications: other ----------------
    ("med.alendronate_70", "medication", "RXNORM", "alendronic acid 70 MG Oral Tablet", None, "904431"),
    ("med.zoledronic_5", "medication", "RXNORM", "zoledronic acid 0.05 MG/ML Injection", None, "705824"),
    ("med.anastrozole_1", "medication", "RXNORM", "anastrozole 1 MG Oral Tablet", None),
    ("med.hydroxyurea_500", "medication", "RXNORM", "hydroxyurea 500 MG Oral Capsule", None),
    ("med.biktarvy", "medication", "RXNORM", "bictegravir 50 MG / emtricitabine 200 MG / tenofovir alafenamide 25 MG Oral Tablet", "1999673"),
    ("med.tamsulosin_04", "medication", "RXNORM", "tamsulosin 0.4 MG Oral Capsule", None),
    ("med.finasteride_5", "medication", "RXNORM", "finasteride 5 MG Oral Tablet", None),

    # ---------------- Vitals / physical measurements (LOINC) ----------------
    ("vital.sbp", "vital", "LNC", "Systolic blood pressure", "8480-6"),
    ("vital.dbp", "vital", "LNC", "Diastolic blood pressure", "8462-4"),
    ("vital.hr", "vital", "LNC", "Heart rate", "8867-4"),
    ("vital.rr", "vital", "LNC", "Respiratory rate", "9279-1"),
    ("vital.temp", "vital", "LNC", "Body temperature", "8310-5"),
    ("vital.spo2", "vital", "LNC", "Oxygen saturation in Arterial blood by Pulse oximetry", "59408-5"),
    ("vital.weight", "vital", "LNC", "Body weight", "29463-7"),
    ("vital.height", "vital", "LNC", "Body height", "8302-2"),
    ("vital.bmi", "vital", "LNC", "Body mass index", "39156-5"),
    ("vital.peak_flow", "vital", "LNC", "Peak expiratory flow rate", "33452-4"),
    ("vital.bp_panel", "vital", "LNC", "Blood pressure panel with all children optional", None),

    # ---------------- Laboratory (LOINC) ----------------
    ("lab.a1c", "lab", "LNC", "Hemoglobin A1c/Hemoglobin.total in Blood", "4548-4"),
    ("lab.glucose", "lab", "LNC", "Glucose [Mass/volume] in Blood", "2339-0"),
    ("lab.creatinine", "lab", "LNC", "Creatinine [Mass/volume] in Serum or Plasma", "2160-0"),
    ("lab.egfr", "lab", "LNC", "Glomerular filtration rate/1.73 sq M.predicted", "33914-3"),
    ("lab.potassium", "lab", "LNC", "Potassium [Moles/volume] in Serum or Plasma", "2823-3"),
    ("lab.sodium", "lab", "LNC", "Sodium [Moles/volume] in Serum or Plasma", "2951-2"),
    ("lab.hgb", "lab", "LNC", "Hemoglobin [Mass/volume] in Blood", "718-7"),
    ("lab.hct", "lab", "LNC", "Hematocrit [Volume Fraction] of Blood by Automated count", None),
    ("lab.wbc", "lab", "LNC", "Leukocytes [#/volume] in Blood by Automated count", None),
    ("lab.platelets", "lab", "LNC", "Platelets [#/volume] in Blood by Automated count", None),
    ("lab.ldl", "lab", "LNC", "Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay", "18262-6"),
    ("lab.hdl", "lab", "LNC", "Cholesterol in HDL [Mass/volume] in Serum or Plasma", "2085-9"),
    ("lab.trig", "lab", "LNC", "Triglyceride [Mass/volume] in Serum or Plasma", "2571-8"),
    ("lab.total_chol", "lab", "LNC", "Cholesterol [Mass/volume] in Serum or Plasma", None),
    ("lab.alt", "lab", "LNC", "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma", None),
    ("lab.ast", "lab", "LNC", "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma", None),
    ("lab.tsh", "lab", "LNC", "Thyrotropin [Units/volume] in Serum or Plasma", "3016-3"),
    ("lab.free_t4", "lab", "LNC", "Thyroxine (T4) free [Mass/volume] in Serum or Plasma", None),
    ("lab.ferritin", "lab", "LNC", "Ferritin [Mass/volume] in Serum or Plasma", "2276-4"),
    ("lab.crp", "lab", "LNC", "C reactive protein [Mass/volume] in Serum or Plasma", "1988-5"),
    ("lab.esr", "lab", "LNC", "Erythrocyte sedimentation rate", None),
    ("lab.uacr", "lab", "LNC", "Albumin/Creatinine [Mass Ratio] in Urine", "9318-7"),
    ("lab.vitamin_d", "lab", "LNC", "25-hydroxyvitamin D [Mass/volume] in Serum or Plasma", "62292-8"),
    ("lab.inr", "lab", "LNC", "INR in Platelet poor plasma by Coagulation assay", "6301-6"),
    ("lab.phq9", "lab", "LNC", "PHQ-9 total score", None),
    ("lab.gad7", "lab", "LNC", "GAD7 total score", None),
    ("lab.cd4", "lab", "LNC", "CD3+CD4+ (T4 helper) cells [#/volume] in Blood", "8122-4"),
    ("lab.hiv_vl", "lab", "LNC", "HIV 1 RNA [#/volume] (viral load) in Serum or Plasma by NAA with probe detection", "20447-9"),
    ("lab.lithium_level", "lab", "LNC", "Lithium [Moles/volume] in Serum or Plasma", "14334-7"),
    ("lab.calprotectin", "lab", "LNC", "Calprotectin [Mass/volume] in Stool", None),
    ("lab.feno", "lab", "LNC", "Nitric oxide [Fraction] in Exhaled gas", None),
    ("lab.eosinophils", "lab", "LNC", "Eosinophils/100 leukocytes in Blood by Automated count", None),
    ("lab.troponin_i", "lab", "LNC", "Troponin I [Mass/volume] in Serum or Plasma", None),
    ("lab.ntprobnp", "lab", "LNC", "Natriuretic peptide B [Mass/volume] in Serum or Plasma", "30934-4"),
    ("lab.ef_echo", "lab", "LNC", "Ejection fraction", None),
    ("lab.ttg_iga", "lab", "LNC", "Tissue transglutaminase IgA [Mass/volume] in Serum", None),
    ("lab.anti_tpo", "lab", "LNC", "Thyroid peroxidase antibody [Units/volume] in Serum", None),
    ("lab.rf", "lab", "LNC", "Rheumatoid factor [Mass/volume] in Serum", None),
    ("lab.anti_ccp", "lab", "LNC", "Cyclic citrullinated peptide antibody", None),
    ("lab.dsdna", "lab", "LNC", "Double stranded DNA antibody", None),
    ("lab.tacrolimus_level", "lab", "LNC", "Tacrolimus [Mass/volume] in Blood", None),
    ("lab.afp", "lab", "LNC", "Alpha-fetoprotein [Mass/volume] in Serum or Plasma", None),
    ("lab.hcv_rna", "lab", "LNC", "Hepatitis C virus RNA [#/volume] in Serum or Plasma by NAA with probe detection", None),
    ("lab.bilirubin_total", "lab", "LNC", "Bilirubin.total [Mass/volume] in Serum or Plasma", None),
    ("lab.albumin", "lab", "LNC", "Albumin [Mass/volume] in Serum or Plasma", None),
    ("lab.alk_phos", "lab", "LNC", "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma", None),
    ("lab.phosphorus", "lab", "LNC", "Phosphorus [Mass/volume] in Serum or Plasma", None),
    ("lab.calcium", "lab", "LNC", "Calcium [Moles/volume] in Serum or Plasma", None),
    ("lab.pth", "lab", "LNC", "Parathyroid hormone [Mass/volume] in Serum or Plasma", None),
    ("lab.psa", "lab", "LNC", "Prostate specific antigen [Mass/volume] in Serum or Plasma", None),
    ("lab.reticulocytes", "lab", "LNC", "Reticulocytes [#/volume] and Reticulocyte fraction", None),
    ("lab.hbf", "lab", "LNC", "Hemoglobin F [Fraction] of total Hemoglobin", None),
    ("lab.hbelectro", "lab", "LNC", "Hemoglobin electrophoresis panel in Blood", None),
    ("lab.ketones", "lab", "LNC", "Ketones [Mass/volume] in Blood", None),
    ("lab.anion_gap", "lab", "LNC", "Anion gap in Serum or Plasma", None),
    ("lab.bicarbonate", "lab", "LNC", "Bicarbonate [Moles/volume] in Serum or Plasma", None),
    ("lab.fev1", "lab", "LNC", "FEV1 [Volume] Respiratory system by Spirometry", None),
    ("lab.fvc", "lab", "LNC", "FVC [Volume] Respiratory system by Spirometry", None),
    ("lab.fev1_fvc", "lab", "LNC", "FEV1/FVC Respiratory system by Spirometry", None),
    ("lab.paco2", "lab", "LNC", "Carbon dioxide [Partial pressure] in Arterial blood", None),
    ("lab.pao2", "lab", "LNC", "Oxygen [Partial pressure] in Arterial blood", None),
    ("lab.urine_protein", "lab", "LNC", "Protein [Mass/volume] in Urine", None),
    ("lab.blood_culture", "lab", "LNC", "Microorganism identified in Blood by Culture", None),
    ("lab.nat_k", "lab", "LNC", "NIH stroke scale medical", None),

    # ---------------- Surveys / social history (LOINC) ----------------
    ("social.smoking_status", "social", "LNC", "Tobacco smoking status", "72166-2"),
    ("social.alcohol", "social", "LNC", "Alcohol consumption", None),
    ("social.exercise", "social", "LNC", "Exercise frequency", None),
    ("social.sdoh", "social", "LNC", "Social determinants of health", None),
    ("social.employment", "social", "LNC", "Employment status", None),
    ("social.education", "social", "LNC", "Education level", None),
    ("social.housing", "social", "LNC", "Housing situation", None),

    # ---------------- Procedures (SNOMED) ----------------
    ("proc.pci_stent", "procedure", "SNOMEDCT_US", "Percutaneous coronary intervention", None, "415070008"),
    ("proc.cardiac_cath", "procedure", "SNOMEDCT_US", "Cardiac catheterization", None),
    ("proc.echo", "procedure", "SNOMEDCT_US", "Echocardiography", None),
    ("proc.ecg", "procedure", "SNOMEDCT_US", "12 lead electrocardiogram at rest", None, "447113005"),
    ("proc.cardiac_rehab", "procedure", "SNOMEDCT_US", "Cardiac rehabilitation", None),
    ("proc.stress_test", "procedure", "SNOMEDCT_US", "Exercise tolerance test", None, "165079009"),
    ("proc.carotid_endarterectomy", "procedure", "SNOMEDCT_US", "Endarterectomy of carotid artery", None),
    ("proc.mri_brain", "procedure", "SNOMEDCT_US", "MRI of brain", None, "816077007"),
    ("proc.ct_head", "procedure", "SNOMEDCT_US", "CT of head and neck", None, "429858000"),
    ("proc.pt", "procedure", "SNOMEDCT_US", "Physical therapy procedure", None, "91251008"),
    ("proc.hemodialysis", "procedure", "SNOMEDCT_US", "Hemodialysis", None),
    ("proc.av_fistula", "procedure", "SNOMEDCT_US", "Creation of arteriovenous fistula", None),
    ("proc.kidney_transplant", "procedure", "SNOMEDCT_US", "Transplantation of kidney", None),
    ("proc.colonoscopy", "procedure", "SNOMEDCT_US", "Colonoscopy", "73761001"),
    ("proc.egd", "procedure", "SNOMEDCT_US", "Esophagogastroduodenoscopy", None),
    ("proc.mri_abdomen", "procedure", "SNOMEDCT_US", "Magnetic resonance imaging of abdomen", None),
    ("proc.spirometry", "procedure", "SNOMEDCT_US", "Spirometry", None),
    ("proc.sixmin_walk", "procedure", "SNOMEDCT_US", "Six minute walk test", None),
    ("proc.oxygen_therapy", "procedure", "SNOMEDCT_US", "Oxygen therapy by inhalation", None),
    ("proc.smoking_cessation", "procedure", "SNOMEDCT_US", "Smoking cessation therapy", None),
    ("proc.eeg", "procedure", "SNOMEDCT_US", "Electroencephalogram", None),
    ("proc.dexa", "procedure", "SNOMEDCT_US", "Dual-energy X-ray absorptiometry", None),
    ("proc.kyphoplasty", "procedure", "SNOMEDCT_US", "Percutaneous vertebroplasty", None),
    ("proc.lumpectomy", "procedure", "SNOMEDCT_US", "Lumpectomy of breast", None, "392021009"),
    ("proc.sentinel_node", "procedure", "SNOMEDCT_US", "Sentinel lymph node biopsy", None),
    ("proc.radiotherapy_breast", "procedure", "SNOMEDCT_US", "Radiotherapy to breast", None, "428923005"),
    ("proc.mammogram", "procedure", "SNOMEDCT_US", "Mammography", None),
    ("proc.blood_transfusion", "procedure", "SNOMEDCT_US", "Transfusion of blood", None),
    ("proc.ultrasound_kidney", "procedure", "SNOMEDCT_US", "Ultrasonography of bilateral kidneys and bladder", None, "1334074007"),
    ("proc.ultrasound_liver", "procedure", "SNOMEDCT_US", "Ultrasonography with contrast", None, "443631006"),
    ("proc.eye_exam", "procedure", "SNOMEDCT_US", "Funduscopy", None),
    ("proc.laser_photo", "procedure", "SNOMEDCT_US", "Photocoagulation", None, "64879003"),
    ("proc.fistula_incision", "procedure", "SNOMEDCT_US", "Incision of anal fistula", None, "79567008"),
    ("proc.synovial_injection", "procedure", "SNOMEDCT_US", "Injection of joint", None),
    ("proc.cpap", "procedure", "SNOMEDCT_US", "Positive airway pressure therapy", None),
    ("proc.sleep_study", "procedure", "SNOMEDCT_US", "Polysomnography", None),
    ("proc.ed_visit", "procedure", "SNOMEDCT_US", "Emergency room admission", None),

    # ---------------- Vaccines (CVX) ----------------
    ("vac.influenza", "vaccine", "CVX", "influenza, seasonal, injectable, preservative free", None, "140"),
    ("vac.covid19", "vaccine", "CVX", "COVID-19 vaccine, mRNA, spike protein", None),
    ("vac.pneumococcal", "vaccine", "CVX", "pneumococcal conjugate PCV15", None),
    ("vac.pneumococcal23", "vaccine", "CVX", "pneumococcal polysaccharide vaccine 23 valent", None),
    ("vac.tdap", "vaccine", "CVX", "Tdap vaccine", None, "115"),
    ("vac.zoster_recomb", "vaccine", "CVX", "zoster vaccine recombinant", None),
    ("vac.hepb", "vaccine", "CVX", "hepatitis b vaccine, adult", None),
    ("vac.hpv", "vaccine", "CVX", "HPV, unspecified formulation", None, "137"),
    ("vac.mmr", "vaccine", "CVX", "measles, mumps, rubella vaccine", None),
    ("vac.hib", "vaccine", "CVX", "Haemophilus influenzae type b vaccine, conjugate unspecified formulation", None, "17"),

    # ---------------- Allergy / intolerance concepts (SNOMED) ----------------
    ("alg.penicillin", "allergy", "SNOMEDCT_US", "Allergy to penicillin", None),
    ("alg.sulfa", "allergy", "SNOMEDCT_US", "Allergy to sulfonamide", None),
    ("alg.aspirin", "allergy", "SNOMEDCT_US", "Allergy to aspirin", None),
    ("alg.latex", "allergy", "SNOMEDCT_US", "Allergy to latex", None),
    ("alg.pollens", "allergy", "SNOMEDCT_US", "Allergy to grass pollen", None, "418689008"),
    ("alg.cat_dander", "allergy", "SNOMEDCT_US", "Allergy to domestic cat protein", None, "1208807009"),
    ("alg.dust_mite", "allergy", "SNOMEDCT_US", "Allergy to house dust mite", None),
    ("alg.peanut", "allergy", "SNOMEDCT_US", "Allergy to peanut", None),
    ("alg.contrast", "allergy", "SNOMEDCT_US", "Allergy to contrast media", None),
    ("alg.codeine", "allergy", "SNOMEDCT_US", "Allergy to codeine", None),
    ("alg.egg", "allergy", "SNOMEDCT_US", "Allergy to egg", None),
    ("alg.shellfish", "allergy", "SNOMEDCT_US", "Allergy to shellfish", None),
]
